### ISSUE TITLE
Maybe add JStachio?

### ISSUE THREAD

**Issue by agentgt** [gunnarmorling/awesome-annotation-processing#22]
Hi folks. I have new annotation processing project. https://github.com/jstachio/jstachio

I [posted it on reddit](https://www.reddit.com/r/java/comments/ya1zw5/quick_preview_of_jstachio_a_type_safe_java/
) (I know gunnar and @rbygrave  are sometimes on reddit so maybe you guys saw it). I plan on early releasing today or Monday to Maven Central. Feel free to wait till then and I will add a comment once that happens.

I wanted to post early to see if there were any other requirements. EDIT the other reason is I am not sure if I should also add this the tools section.

JStachio is kind of a double APT project in that it uses the annotation processing framework to generate typesafe Mustache templates for web development BUT it can also be used for code generation which is usually useful for other APT projects. (perhaps MapStruct will use it instead of freemarker someday... I'm kidding freemarker is pretty awesome :) ). 

I plan on some point making a JStachio option that will require zero runtime and thus no need to maven shade for annotation processors.

**Comment by gunnarmorling** [comment]
Added it, thx!
