### ISSUE TITLE
Potential new compiler testing tool for Java 11+

### ISSUE THREAD

**Issue by ascopes** [gunnarmorling/awesome-annotation-processing#24]
Hello!

I am currently working on a project that aims to implement compiler testing facilities for Java 11 and newer. Was wondering if this would be useful to add to the list eventually if you are interested.

Don't want to come across as making unwanted advertising, as that is definitely not my aim, but feedback from anyone who is interested in the mean time would always be welcome and useful to me, which is why I decided to ask.

The primary aim is to provide an interface that is compatible with the most bleeding edge of JDK releases to enable writing forwards-compatible and future proof annotation processors and plugins. It can also be used to integration test generated source code from codegen libraries. Additionally, you can make use of classloaders directly for generated code -- allowing you to immediately load classes generated from code under test into memory and use them with the reflection API or via dynamic typing in languages like Apache Groovy.

The project itself is still under development, but it has a few additional aims that I found the Google compiler testing module I used to work with didn't seem to support. Specifically this includes providing full JPMS support, allowing support for alternative compiler implementations other than javac, JUnit5 integration, etc. It also makes use of actual file systems that can be accessed from outside the filer API since many annotation processor libraries tend to do this. This is implemented using JIMFS by default which is effectively a pure Java RAM disk. However, a java.io.File-compatible API is also supported.

I am also looking for candidates for compiler plugins and annotation processors that will make for good acceptance tests on my side. The JSR-199 compiler plugin can be a little ambiguous in places and some annotation processor libraries can use compiler internals in surprising ways, so one of my aims is to have a large number of acceptance tests for various libraries in the repo that are run on every build to ensure no surprising behaviour has been missed. At the time of writing, I am currently testing against google autofactory, google autoservice, google autovalue, checkerframework, google dagger, spring indexer, spring boot autoconfiguration processor, spring boot configuration processor, mapstruct, lombok, manifold, and immutables.

Project is over at https://github.com/ascopes/java-compiler-testing. I aim to have a stable release by March if not sooner.

If you are interested then that would be fantastic, but if you are not, then no worries at all. Thought I would ask though! Thanks in advance!

**Comment by gunnarmorling** [comment]
Sounds like an interesting project and definitely worth being added to the list. PR welcome!

**Comment by ascopes** [comment]
Thanks! Once it is ready, I will pop one up!
